### PR TITLE
sub

### PR DESCRIPTION
**Pull request by kuzuha**

### CODE REVIEW

**Comment by tinbotu** [comment]
very bad

**Comment by tinbotu** [comment]
LBTM

**Comment by ykic** [comment]
not enoug

**Comment by tinbotu** [comment]
@takano32 will you swear to recognize that I am abosolutely mainculture?

**Comment by takano32** [comment]
@tinbotu ?

**Comment by tinbotu** [comment]
I reopen if i was **abosolutely** **mainculture**

**Pull request closed without merging**
